### PR TITLE
Bulk add kaomojis

### LINKED ISSUE #1: Incorporate kaomoji database from Peachy
There are a bunch of kaomojis here with tags:
https://github.com/itsmeichigo/peachy/blob/main/Peachy/kaomoji.json
But they don't have names so I'm not sure how you'd want to deal with that. Maybe concatenate the tags with a counter like `whatever_shrug_1`, `whatever_shrug_2`.

### PR DESCRIPTION
**Pull request by andrew222651**
Closes #1

### CODE REVIEW

**Comment by andrew222651** [comment]
The first commit removes some duplicates in the existing json file. There's one duplicate that wasn't removed, called `"could_not_find_items_that_match_search_term"` which is the same as `"bear_flip_table"`. I thought it might have a special meaning.

**Comment by andrew222651** [comment]
Unfortunately all the ones I added I put as UNASSIGNED

**Comment by iansinnott** [comment]
Thanks!

**Comment by andrew222651** [comment]
@iansinnott cool, looking forward to using them when asciilib.iansinnott.com is updated

**Comment by iansinnott** [comment]
yeah was just looking at that. I'd like to transition it from gatsby to
next.js, so it may take a bit more to get updated. should also figure out a
CI approach so that it stays up to date with asciilib… although this
project doesn't update often so on second thought, no need.

**Comment by iansinnott** [comment]
Updated

**Pull request merged**
